version: 2
registries:
  github-antafes-maven:
    type: maven-repository
    url: https://maven.pkg.github.com/antafes/MyXML
    username: antafes
    password: ${{secrets.DEPENDABOT_GITHUB_ACCESS_TOKEN}}

updates:
  - package-ecosystem: maven
    directory: "/"
    registries:
      - github-antafes-maven
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: UTC
    labels:
      - dependencies
      - type:dependencies
    assignees:
      - Antafes
    reviewers:
      - Antafes
    open-pull-requests-limit: 5

