spring:
  application:
    name: Vampire Editor (Test)
  main:
    web-application-type: none
    lazy-initialization: false
  jmx:
    enabled: false

logging:
  level:
    antafes: INFO
    org.springframework: WARN

vampire:
  config:
    path: ${java.io.tmpdir}/vampire-editor-tests/.vampire/

