resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
- name: vampire-editor-repo
  type: git
  source:
    uri: https://github.com/Antafes/Vampire-Editor
    branch: master
    private_key: ((private_key))
- name: vampire-editor-repo-dev
  type: git
  source:
    uri: https://github.com/Antafes/Vampire-Editor
    branch: dev
    private_key: ((private_key))
- name: vampire-editor-repo-pr
  type: pull-request
  check_every: 10m
  source:
    repository: Antafes/Vampire-Editor
    access_token: ((acccess_token))
- name: vampire-editor-pre-release
  type: github-release
  source:
    owner: Antafes
    repository: Vampire-Editor
    pre_release: true
    release: false
    access_token: ((acccess_token))
- name: vampire-editor-release
  type: github-release
  source:
    owner: Antafes
    repository: Vampire-Editor
    release: true
    drafts: true
    access_token: ((acccess_token))
- name: myXML-lib
  type: github-release
  source:
    owner: Antafes
    repository: MyXML
    release: true
    access_token: ((acccess_token))

jobs:
- name: vampire-editor-pr
  plan:
    - get: vampire-editor-repo-pr
      trigger: true
      version: every
    - get: myXML-lib
    - put: vampire-editor-repo-pr
      params:
        path: vampire-editor-repo-pr
        status: pending
    - task: unit-test
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: frekele/ant
            tag: 1.10-jdk8
        inputs:
          - name: vampire-editor-repo-pr
          - name: myXML-lib
        outputs:
          - name: dist
        run:
          path: ci/test.sh
          dir: vampire-editor-repo-pr
      on_failure:
        put: vampire-editor-repo-pr
        params:
          path: vampire-editor-repo-pr
          status: failure
    - put: vampire-editor-repo-pr
      params:
        path: vampire-editor-repo-pr
        status: success

- name: vampire-editor-dev
  plan:
  - get: vampire-editor-pre-release
  - get: vampire-editor-repo-dev
    trigger: true
  - get: myXML-lib
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: frekele/ant
          tag: 1.10-jdk8
      inputs:
      - name: vampire-editor-pre-release
      - name: vampire-editor-repo-dev
      - name: myXML-lib
      outputs:
      - name: dist
      run:
        path: ci/build-dev.sh
        dir: vampire-editor-repo
  - put: vampire-editor-pre-release
    params:
     name: dist/name
     tag: dist/tag
     globs:
      - dist/VampireEditor.zip
  - put: vampire-editor-repo-dev
    params:
      repository: vampire-editor-repo

- name: vampire-editor
  plan:
  - get: vampire-editor-repo
    trigger: true
  - get: vampire-editor-pre-release
  - get: myXML-lib
  - task: check-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: debian
          tag: stable-slim
      inputs:
      - name: vampire-editor-repo
      - name: vampire-editor-pre-release
      run:
        path: ci/check-version.sh
        dir: vampire-editor-repo
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: frekele/ant
          tag: 1.10-jdk8
      inputs:
      - name: vampire-editor-repo
      - name: myXML-lib
      outputs:
      - name: dist
      run:
        path: ci/build.sh
        dir: vampire-editor-repo
  - put: vampire-editor-release
    params:
      name: dist/name
      tag: dist/tag
      globs:
      - dist/VampireEditor.zip