resources:
- name: vampire-editor-repo
  type: git
  source:
    uri: https://github.com/Antafes/Vampire-Editor
    branch: concourse-test
- name: vampire-editor-release
  type: github-release
  source:
    owner: Antafes
    repository: Vampire_Editor
    pre_release: true
- name: myXML-lib
  type: github-release
  source:
    owner: Antafes
    repository: MyXML
    release: true
jobs:
- name: vampire-editor-dev
  plan:
  - get: vampire-editor-repo
    trigger: true
  - get: myXML-lib
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: frekele/ant
          tag: 1.10-jdk8
      inputs:
      - name: vampire-editor-repo
      - name: myXML-lib
      outputs:
      - name: dist
      run:
        path: ci/build.sh
        dir: vampire-editor-repo